// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUvlliH7BrtRsCBdqMHQpFqt5yOG28kOI',
    appId: '1:546926748083:web:0655a19812697f304febc6',
    messagingSenderId: '546926748083',
    projectId: 'fir-flutter-codelab-7394e',
    authDomain: 'fir-flutter-codelab-7394e.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-7394e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLDB-dvArKUa0O8lQV65_Va2uo0Z4Nd3Q',
    appId: '1:546926748083:android:d73602fa8f873ccf4febc6',
    messagingSenderId: '546926748083',
    projectId: 'fir-flutter-codelab-7394e',
    storageBucket: 'fir-flutter-codelab-7394e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaiP7R7xKXai64dUGOHx79w6fyxBKS618',
    appId: '1:546926748083:ios:8276b3c3ed0fdf2c4febc6',
    messagingSenderId: '546926748083',
    projectId: 'fir-flutter-codelab-7394e',
    storageBucket: 'fir-flutter-codelab-7394e.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaiP7R7xKXai64dUGOHx79w6fyxBKS618',
    appId: '1:546926748083:ios:8276b3c3ed0fdf2c4febc6',
    messagingSenderId: '546926748083',
    projectId: 'fir-flutter-codelab-7394e',
    storageBucket: 'fir-flutter-codelab-7394e.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

}